name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps: 
    - name: buildstep1_1
      uses: actions/checkout@v4

  buildjob2:
    runs-on: ubuntu-latest
    steps:
    - name: buildstep2_1
      uses: actions/checkout@v4
